add cros for certbot

diff --git a/docker-compose.prod.yml b/docker-compose.prod.yml
--- a/docker-compose.prod.yml
+++ b/docker-compose.prod.yml
@@ -29,9 +29,11 @@ services:
     volumes:
       - ./web-app/.well-known/acme-challenge:/var/www/html/.well-known/acme-challenge  # ACME challenge folder
       - ./web-app/ssl:/etc/letsencrypt # Mount SSL keys
+    environment:
+      - CERTBOT_MODE=${CERTBOT_MODE:-generate} # Mode: 'generate' or 'renew'
     entrypoint: >
       sh -c "
-      if [ ! -f /etc/letsencrypt/live/${DOMAIN}/fullchain.pem ]; then
+      if [ \"$CERTBOT_MODE\" = \"generate\" ]; then
         certbot certonly \
           --non-interactive \
           --webroot \
@@ -40,24 +42,26 @@ services:
           --agree-tos \
           -d ${DOMAIN},www.${DOMAIN} \
           --debug --verbose;
+      elif [ \"$CERTBOT_MODE\" = \"renew\" ]; then
+        certbot renew --quiet;
       else
-        certbot renew;
-      fi;"
+        echo 'Invalid CERTBOT_MODE specified. Use generate or renew.';
+        exit 1;
+      fi"
     networks:
       - app-network
 
-  # certbot-cron:
-  #   image: alpine
-  #   container_name: certbot-cron
-  #   volumes:
-  #     - /var/run/docker.sock:/var/run/docker.sock # Required to restart or run containers
-  #   entrypoint: >
-  #     sh -c "
-  #     echo '0 */12 * * * docker-compose run certbot' > /etc/crontabs/root &&
-  #     crond -f -d 8
-  #     "
-  #   networks:
-  #     - app-network
+  cron:
+    image: bash:latest
+    container_name: certbot-cron
+    depends_on:
+      - certbot
+    volumes:
+      - /etc/localtime:/etc/localtime:ro
+    command: >
+      sh -c "
+      echo '0 0 * * * docker-compose run --rm certbot CERTBOT_MODE=renew' > /etc/crontab &&
+      crond -f"
 
 networks:
   app-network:
